### ISSUE TITLE
hnn install on Windows 8.1 fails

### ISSUE THREAD

**Issue by tmedzhitov** [alpmestan/hnn#1]
Hello,

I wanted to install the "hnn" package on my Windows 8.1 system, and I got the below error.

Please advise. Thanks.
P.S. I am new to Haskell, but looks like I followed the common instructions... 

C:\Projects\Haskell>CABAL install hnn
Resolving dependencies...
Configuring hmatrix-0.16.1.0...
Failed to install hmatrix-0.16.1.0
Last 10 lines of the build log ( C:\Users\TIMUR\AppData\Roaming\cabal\logs\hmatrix-0.16.1.0.log ):
Configuring hmatrix-0.16.1.0...
setup-Cabal-1.18.1.3-x86_64-windows-ghc-7.8.3.exe: Missing dependencies on
foreign libraries:
* Missing C libraries: blas, lapack, blas, lapack
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
CABAL: Error: some packages failed to install:
hmatrix-0.16.1.0 failed during the configure step. The exception was:
ExitFailure 1
hnn-0.2.0.0 depends on hmatrix-0.16.1.0 which failed to install.

**Comment by tmedzhitov** [comment]
Thank you, I will try.

**Comment by varosi** [comment]
For me those instructions are not working.

**Comment by alpmestan** [comment]
You probably should report that in hmatrix's bug tracker, let me know if something can be done on the *hnn* side to help.

**Comment by varosi** [comment]
I have sent fixes for hmatrix. So latest 0.17.0.1 version should work on Windows, built with OpenBLAS library.

Related https://github.com/albertoruiz/hmatrix/pull/148

**Comment by alpmestan** [comment]
Sweet, we can close this issue for good then I suppose?

**Comment by varosi** [comment]
If hnn depend on that latest hmatrix version I suppose.

**Comment by alpmestan** [comment]
It should be picked up automatically as long as folks do a `cabal update` first.

**Comment by varosi** [comment]
Yes, but this issue is fixed only for hmatrix >= 0.17.0.1, not >= 0.16 as it is now.

**Comment by alpmestan** [comment]
Right, but earlier versions of hmatrix work fine with *hnn* on other OSes, so I'd have to put a conditional bound only for Windows, don't feel too comfortable doing that. I'll probably do the change you suggest in a month or something, when it's "less unreasonable" to ask for the latest hmatrix.

**Comment by varosi** [comment]
okay, no worries
