### ISSUE TITLE
README.md has broken link to repo

### ISSUE THREAD

**Issue by AleXoundOS** [alpmestan/hnn#13]
In the first sentence: "You can find online documentation of approximately the latest version of this repo **here**..." the link is broken -- returns 404.

**Comment by alpmestan** [comment]
Yes sorry. The documentation is available [on hackage](https://hackage.haskell.org/package/hnn-0.3/docs/AI-HNN-FF-Network.html) though. I'll fix the link in the README as well.

**Comment by alpmestan** [comment]
Done
