### ISSUE TITLE
Bit rotted and won't install

### ISSUE THREAD

**Issue by TomMD** [alpmestan/hnn#9]
See the below errors:

```
AI/HNN/Recurrent/Network.hs:93:5: Not in scope: ‘mapVector’

AI/HNN/Recurrent/Network.hs:93:29: Not in scope: ‘zipVectorWith’

AI/HNN/Recurrent/Network.hs:95:20:
    Not in scope: ‘Numeric.LinearAlgebra.join’
    Perhaps you meant one of these:
      ‘Numeric.LinearAlgebra.vjoin’ (imported from Numeric.LinearAlgebra),
```

**Comment by alpmestan** [comment]
I have been working on and off on a complete rewrite of this library, but in the version that's out there, only the feed forward module works correctly. I can make a release with the rest stripped off, if you want.

**Comment by cheecheeo** [comment]
:+1: for a release with the rest stripped off.

**Comment by alpmestan** [comment]
[Done](http://hackage.haskell.org/package/hnn-0.3).
